name: github pages

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
                node-version: '14'
        
        - run: git config --global user.email "chanyoungs@gmail.com"
        - run: git config --global user.name "chanyoungs"

        - name: NPM install
          run: npm install
        
        - name: Deploy with gh-pages
          run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
